--------------------------------------------------------------
--                    direct_access.lua                     --
--------------------------------------------------------------
--                                                          --
-- This file provides the 2 public modder-facing functions  --
-- for accessing game_doc data. These are:                  --
--                                                          --
-- <> game_doc.get_doc_data()                               --
-- <> game_doc.get_hidden_data()                            --
--                                                          --
-- Use the above functions to access and possibly make      --
-- changes to the backend data in game_doc                  --
--------------------------------------------------------------

